### PR TITLE
fix flake8 reported issues, run tests

### PR DESCRIPTION
**Pull request by sandrobonazzola**
Cleaned up the code, added automated tests.

Not adding all the unit tests at once as they are failing on my laptop. I'll enable all tests in a different PR once this is in.

# Coverage report: 25%

coverage.py v6.5.0, created at 2022-10-24 13:57 +0000 

Module | statements | missing | excluded | coverage  
---|---|---|---|---  
drop_buffer_cache.py | 33 | 15 | 0 | 55%  
fallocate.py | 35 | 17 | 0 | 51%  
parser_data_types.py | 49 | 27 | 0 | 45%  
smallfile.py | 1450 | 1181 | 0 | 19%  
smf_test_params.py | 98 | 69 | 0 | 30%  
sync_files.py | 47 | 36 | 0 | 23%  
yaml_parser.py | 146 | 57 | 0 | 61%  
Total | 1858 | 1402 | 0 | 25%  
  
coverage.py v6.5.0, created at 2022-10-24 13:57 +0000 

Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>

### CODE REVIEW

**Comment by sandrobonazzola** [comment]
No, didn't run black. Run flake8 and isort and manually fixed stuff reported there.

**Comment by portante** [comment]
> No, didn't run black. Run flake8 and isort and manually fixed stuff reported there.

Have you considered using `black`?  It'd make these changes much easier to consume in review.

**Comment by sandrobonazzola** [comment]
pushed an additional commit with black run.

**Comment by sandrobonazzola** [comment]
Had to drop both isort and flake8  as they don't agree with black.

**Comment by portante** [comment]
Here is a PR which just applies `black` and `isort` without any other changes, https://github.com/distributed-system-analysis/smallfile/pull/37.

**Comment by portante** [comment]
If we take that PR in first, and then rebase this PR on that, we'll have just the fixes you have applied which will be a bit easier to review.

**Comment by sandrobonazzola** [comment]
ok, go ahead merging #37 and I'll rebase.

**Comment by sandrobonazzola** [comment]
moved to #38 due to master/main rename

**Pull request closed without merging**
